NightMusicTable:
night_music: MACRO
	db \1, \2
    ;\1 - original song
    ;\2 - night song
ENDM
	night_music MUSIC_NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN_NIGHT
    night_music MUSIC_ROUTE_29, MUSIC_ROUTE_29_NIGHT
    night_music MUSIC_CHERRYGROVE_CITY, MUSIC_CHERRYGROVE_CITY_NIGHT
    night_music MUSIC_ROUTE_30, MUSIC_ROUTE_30_NIGHT
    night_music MUSIC_VIOLET_CITY, MUSIC_VIOLET_CITY_NIGHT
	night_music MUSIC_AZALEA_TOWN, MUSIC_AZALEA_TOWN_NIGHT
	night_music MUSIC_ROUTE_32, MUSIC_ROUTE_32_NIGHT
	night_music MUSIC_GOLDENROD_CITY, MUSIC_GOLDENROD_CITY_NIGHT
	night_music MUSIC_ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY_NIGHT
	night_music MUSIC_ROUTE_38, MUSIC_ROUTE_38_NIGHT
	night_music MUSIC_ROUTE_42, MUSIC_ROUTE_42_NIGHT
	night_music MUSIC_ROUTE_26, MUSIC_ROUTE_26_NIGHT
    night_music MUSIC_POKEMON_CENTER, MUSIC_POKEMON_CENTER_NIGHT
	db -1 ; end
